name: Abdulrahmon Yusuf
logo: Screenshot_20241030-112933~2.png
description: Data Analyst 
email: adedoyinyusuf997@gmail.com
linkedin: www.linkedin.com/in/abdulrahmon-yusuf
showdownloads: false
theme: jekyll-theme-minimal
